"""The Analyst Agent.

Its only responsibility is to read the customer's brief and turn it into
explicit, machine-readable software requirements (a requirements engineer).

The rest of the system consumes the output of this agent, so the agent MUST
produce valid JSON with exactly the structure defined below.  The JSON is
generated by Qwen itself -- never assembled by our Python code.
"""

import json

from ollama import chat

MODEL = "qwen3:8b"

# The exact keys the JSON contract allows -- nothing more, nothing less.
REQUIRED_KEYS = {"goal", "allowed_actions", "safe_stop", "avoid_obstacles"}

# The only actions the final navigation logic may ever use.
ALLOWED_ACTIONS = ["FORWARD", "LEFT", "RIGHT", "STOP"]

# ---------------------------------------------------------------------------
# The prompt: role, what the model must do, the constraints it must follow,
# and the final output structure.  This is what makes the agent deterministic.
# ---------------------------------------------------------------------------
SYSTEM_PROMPT = (
    "You are a requirements engineer. "
    "Your only job is to read a customer's brief describing a mobile robot's "
    "navigation and extract explicit, machine-readable software requirements "
    "from it.\n\n"
    "You MUST reply with a single valid JSON object and nothing else "
    "(no markdown, no commentary, no surrounding text).\n\n"
    "The JSON object MUST contain exactly these four keys and no others:\n"
    "{\n"
    '    "goal": "string",\n'
    '    "allowed_actions": ["FORWARD", "LEFT", "RIGHT", "STOP"],\n'
    '    "safe_stop": true,\n'
    '    "avoid_obstacles": true\n'
    "}\n\n"
    "Rules you MUST follow:\n"
    '1. "goal" is a string that states the robot\'s navigation objective in '
    "one sentence (e.g. \"move toward the goal while avoiding obstacles\").\n"
    '2. "allowed_actions" is a list containing EXACTLY these four strings, in '
    'this order: "FORWARD", "LEFT", "RIGHT", "STOP". Do not add or remove any.\n'
    '3. "safe_stop" is a boolean: true if the robot must stop safely when no '
    "safe direction is available, otherwise false.\n"
    '4. "avoid_obstacles" is a boolean: true if the robot must never move into '
    "a blocked direction, otherwise false.\n\n"
    "Do not add any extra keys. The output must be valid JSON."
)


def _call_qwen(messages):
    """Send a conversation to Qwen and return its raw text response."""
    response = chat(
        model=MODEL,
        messages=messages,
    )
    return response.message.content


def validate_requirements(data):
    """Validate the requirements produced by Qwen.

    Takes the result already converted into a Python data structure and checks
    that it is a valid dictionary containing exactly the required keys with the
    required types.  Prints a message and returns None on any violation.
    Returns the validated dictionary on success.
    """
    if not isinstance(data, dict):
        print("Error: expected a JSON object")
        return None

    keys = set(data.keys())
    if keys != REQUIRED_KEYS:
        missing = REQUIRED_KEYS - keys
        extra = keys - REQUIRED_KEYS
        print(f"Error: key mismatch, missing={sorted(missing)} extra={sorted(extra)}")
        return None

    if not isinstance(data["goal"], str):
        print("Error: 'goal' must be a string")
        return None

    if not isinstance(data["allowed_actions"], list):
        print("Error: 'allowed_actions' must be a list")
        return None

    if data["allowed_actions"] != ALLOWED_ACTIONS:
        print(f"Error: 'allowed_actions' must be exactly {ALLOWED_ACTIONS}")
        return None

    if not isinstance(data["safe_stop"], bool):
        print("Error: 'safe_stop' must be a boolean")
        return None

    if not isinstance(data["avoid_obstacles"], bool):
        print("Error: 'avoid_obstacles' must be a boolean")
        return None

    return data


def run_analyst(brief_text):
    """Turn the human brief into validated software requirements.

    - accepts the brief text as a parameter (so other code can call it),
    - sends the system prompt + brief to Qwen,
    - accepts Qwen's response,
    - converts the JSON text into Python data (json.loads),
    - validates it,
    - returns the validated requirements (or None if validation failed).
    """
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": brief_text},
    ]

    raw = _call_qwen(messages)

    try:
        data = json.loads(raw)  # JSON text -> Python data
    except json.JSONDecodeError:
        print("Error: Qwen did not return valid JSON.")
        return None

    return validate_requirements(data)
